server:
  port: 8082
  servlet:
    context-path: /product

app:
  mongodb:
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    s3-bucket-name: ${AWS_S3_BUCKET_NAME}
    cloudfront-url: ${AWS_CLOUDFRONT_URL}

spring:
  application:
    name: product-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30